import { prisma } from "@/lib/db";
import { NextRequest, NextResponse } from "next/server";

interface NavigatorTechnique {
  techniqueID: string;
  tactic?: string;
  color: string;
  comment: string;
  score: number;
  enabled: boolean;
}

interface NavigatorLayer {
  name: string;
  versions: { attack: string; navigator: string; layer: string };
  domain: string;
  description: string;
  filters: { platforms: string[] };
  sorting: number;
  layout: { layout: string; showID: boolean; showName: boolean; showAggregateScores: boolean; countUnscored: boolean; aggregateFunction: string };
  hideDisabled: boolean;
  techniques: NavigatorTechnique[];
  gradient: { colors: string[]; minValue: number; maxValue: number };
  legendItems: { label: string; color: string }[];
  metadata: { name: string; value: string }[];
  showTacticRowBackground: boolean;
  tacticRowBackground: string;
  selectTechniquesAcrossTactics: boolean;
  selectSubtechniquesWithParent: boolean;
  selectVisibleTechniques: boolean;
}

const TACTIC_SHORT_NAMES: Record<string, string> = {
  "Reconnaissance": "reconnaissance",
  "Resource Development": "resource-development",
  "Initial Access": "initial-access",
  "Execution": "execution",
  "Persistence": "persistence",
  "Privilege Escalation": "privilege-escalation",
  "Defense Evasion": "defense-evasion",
  "Credential Access": "credential-access",
  "Discovery": "discovery",
  "Lateral Movement": "lateral-movement",
  "Collection": "collection",
  "Command and Control": "command-and-control",
  "Exfiltration": "exfiltration",
  "Impact": "impact",
};

function buildLayer(
  name: string,
  description: string,
  techniques: { externalId: string; tacticNames: string[]; score: number; comment: string }[],
  color: string,
): NavigatorLayer {
  const maxScore = Math.max(...techniques.map((t) => t.score), 1);

  const navTechniques: NavigatorTechnique[] = [];
  for (const t of techniques) {
    const tactics = t.tacticNames.map((n) => TACTIC_SHORT_NAMES[n]).filter(Boolean);
    if (tactics.length === 0) {
      navTechniques.push({
        techniqueID: t.externalId,
        color,
        comment: t.comment,
        score: t.score,
        enabled: true,
      });
    } else {
      for (const tactic of tactics) {
        navTechniques.push({
          techniqueID: t.externalId,
          tactic,
          color,
          comment: t.comment,
          score: t.score,
          enabled: true,
        });
      }
    }
  }

  return {
    name,
    versions: { attack: "16", navigator: "5.1.0", layer: "4.5" },
    domain: "enterprise-attack",
    description,
    filters: { platforms: ["Windows", "Linux", "macOS", "Network", "Cloud", "Containers"] },
    sorting: 0,
    layout: {
      layout: "side",
      showID: true,
      showName: true,
      showAggregateScores: false,
      countUnscored: false,
      aggregateFunction: "average",
    },
    hideDisabled: false,
    techniques: navTechniques,
    gradient: {
      colors: ["#ffffff", color],
      minValue: 0,
      maxValue: maxScore,
    },
    legendItems: [
      { label: "Used", color },
    ],
    metadata: [
      { name: "Generated by", value: "TI-Rex" },
      { name: "Generated at", value: new Date().toISOString() },
    ],
    showTacticRowBackground: false,
    tacticRowBackground: "#dddddd",
    selectTechniquesAcrossTactics: true,
    selectSubtechniquesWithParent: false,
    selectVisibleTechniques: false,
  };
}

async function buildActorLayer(actorId: string) {
  const actor = await prisma.threatActor.findUnique({
    where: { id: actorId },
    select: {
      name: true,
      externalId: true,
      country: true,
      procedures: {
        include: {
          technique: {
            select: {
              externalId: true,
              tactics: { include: { tactic: { select: { name: true } } } },
            },
          },
        },
      },
    },
  });

  if (!actor) return null;

  const techMap = new Map<string, { tacticNames: string[]; count: number }>();
  for (const p of actor.procedures) {
    const existing = techMap.get(p.technique.externalId);
    const tactics = p.technique.tactics.map((tt) => tt.tactic.name);
    if (existing) {
      existing.count++;
      for (const t of tactics) {
        if (!existing.tacticNames.includes(t)) existing.tacticNames.push(t);
      }
    } else {
      techMap.set(p.technique.externalId, { tacticNames: tactics, count: 1 });
    }
  }

  const techniques = [...techMap.entries()].map(([externalId, data]) => ({
    externalId,
    tacticNames: data.tacticNames,
    score: data.count,
    comment: `${data.count} procedure(s) documented`,
  }));

  const desc = `Techniques used by ${actor.name} (${actor.externalId})${actor.country ? ` — ${actor.country}` : ""}`;
  return buildLayer(actor.name, desc, techniques, "#e60000");
}

async function buildMalwareLayer(malwareId: string) {
  const malware = await prisma.malware.findUnique({
    where: { id: malwareId },
    select: {
      name: true,
      externalId: true,
      type: true,
      procedures: {
        include: {
          technique: {
            select: {
              externalId: true,
              tactics: { include: { tactic: { select: { name: true } } } },
            },
          },
        },
      },
    },
  });

  if (!malware) return null;

  const techMap = new Map<string, { tacticNames: string[]; count: number }>();
  for (const p of malware.procedures) {
    const existing = techMap.get(p.technique.externalId);
    const tactics = p.technique.tactics.map((tt) => tt.tactic.name);
    if (existing) {
      existing.count++;
      for (const t of tactics) {
        if (!existing.tacticNames.includes(t)) existing.tacticNames.push(t);
      }
    } else {
      techMap.set(p.technique.externalId, { tacticNames: tactics, count: 1 });
    }
  }

  const techniques = [...techMap.entries()].map(([externalId, data]) => ({
    externalId,
    tacticNames: data.tacticNames,
    score: data.count,
    comment: `${data.count} procedure(s)`,
  }));

  const desc = `Techniques used by ${malware.name} (${malware.externalId})${malware.type ? ` [${malware.type}]` : ""}`;
  return buildLayer(malware.name, desc, techniques, "#9b59b6");
}

async function buildCategoryLayer(slug: string) {
  const category = await prisma.category.findUnique({
    where: { slug },
    include: {
      techniques: {
        include: {
          technique: {
            select: {
              externalId: true,
              tactics: { include: { tactic: { select: { name: true } } } },
              _count: { select: { procedures: true } },
            },
          },
        },
      },
    },
  });

  if (!category) return null;

  const techniques = category.techniques.map((ct) => ({
    externalId: ct.technique.externalId,
    tacticNames: ct.technique.tactics.map((tt) => tt.tactic.name),
    score: ct.technique._count.procedures || 1,
    comment: `${ct.technique._count.procedures} procedure(s)`,
  }));

  return buildLayer(
    category.name,
    category.description ?? `${category.name} techniques`,
    techniques,
    category.color ?? "#3498db",
  );
}

async function buildComparisonLayer(actorIds: string[]) {
  const actors = await prisma.threatActor.findMany({
    where: { id: { in: actorIds } },
    select: {
      name: true,
      procedures: {
        include: {
          technique: {
            select: {
              externalId: true,
              tactics: { include: { tactic: { select: { name: true } } } },
            },
          },
        },
      },
    },
  });

  const techMap = new Map<string, { tacticNames: string[]; actors: Set<string> }>();
  for (const actor of actors) {
    for (const p of actor.procedures) {
      const existing = techMap.get(p.technique.externalId);
      const tactics = p.technique.tactics.map((tt) => tt.tactic.name);
      if (existing) {
        existing.actors.add(actor.name);
        for (const t of tactics) {
          if (!existing.tacticNames.includes(t)) existing.tacticNames.push(t);
        }
      } else {
        techMap.set(p.technique.externalId, { tacticNames: tactics, actors: new Set([actor.name]) });
      }
    }
  }

  const techniques = [...techMap.entries()].map(([externalId, data]) => ({
    externalId,
    tacticNames: data.tacticNames,
    score: data.actors.size,
    comment: `Used by: ${[...data.actors].join(", ")}`,
  }));

  const names = actors.map((a) => a.name).join(" vs ");
  return buildLayer(
    `Comparison: ${names}`,
    `Technique overlap between ${actors.length} threat actors`,
    techniques,
    "#e67e22",
  );
}

export async function GET(request: NextRequest) {
  const { searchParams } = request.nextUrl;
  const type = searchParams.get("type");
  const id = searchParams.get("id");
  const ids = searchParams.get("ids");

  let layer: NavigatorLayer | null = null;

  if (type === "actor" && id) {
    layer = await buildActorLayer(id);
  } else if (type === "malware" && id) {
    layer = await buildMalwareLayer(id);
  } else if (type === "category" && id) {
    layer = await buildCategoryLayer(id);
  } else if (type === "comparison" && ids) {
    const actorIds = ids.split(",").filter(Boolean);
    if (actorIds.length > 0) {
      layer = await buildComparisonLayer(actorIds);
    }
  }

  if (!layer) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  const filename = `${layer.name.replace(/[^a-zA-Z0-9]/g, "_")}_layer.json`;

  return new NextResponse(JSON.stringify(layer, null, 2), {
    headers: {
      "Content-Type": "application/json",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}
